import { addStrings } from '../../shared/i18n.js';

addStrings('ru', {
  'con.title': 'Афера',
  'con.tagline': 'камень-ножницы-бумага, где на кону — карты с именами',
  'con.players': 'Игроков:',
  'con.mode': 'Играем:',
  'con.mode.pvp': 'все люди за одним экраном',
  'con.mode.easy': 'с компьютером (простой)',
  'con.mode.normal': 'с компьютером (хитрый)',
  'con.rounds': 'Раундов:',
  'con.again': 'ещё раз!',
  'con.p0': 'Синий',
  'con.p1': 'Красный',
  'con.p2': 'Зелёный',
  'con.p3': 'Лиловый',
  'con.cpu1': 'Жулик',
  'con.cpu2': 'Плут',
  'con.cpu3': 'Ловкач',
  'con.pts': ['очко', 'очка', 'очков'],
  'con.cards': ['карта', 'карты', 'карт'],
  'con.type0': 'камень',
  'con.type1': 'бумага',
  'con.type2': 'ножницы',
  'con.round': 'раунд {r} из {n}',
  'con.turn': '{name}: ваш ход · {round}',
  'con.turn.you': 'Ваш ход · {round}',
  'con.turn.them': 'Ходит {name}…',
  'con.thinking': '{name} думает…',
  'con.defend': '{name}, вас вызывают на бой!',
  'con.defend.you': 'Вас вызывают на бой!',
  'con.trade.you': 'Вам предлагают обмен',
  'con.trade.them': '{name} думает над обменом…',
  'con.setup.you': 'Разметьте свои карты',
  'con.setup.name': '{name}: разметьте свои карты',
  'con.setup.wait': 'Соперники размечают карты…',
  'con.cover.status': 'Очередь: {name}',
  'con.cover.title': 'Передайте устройство',
  'con.cover.note': 'остальные — не подглядывать!',
  'con.cover.btn': 'Это я — показать карты',
  'con.online.wait': 'Ждём второго игрока…',
  'con.online.note': 'Число игроков, раундов и новую партию выбирает создатель комнаты. Втроём и вчетвером за свободные места играет компьютер; кто подключится посреди партии, занимает место компьютера вместе с его картами.',
  'con.online.waitnew': 'Новую партию начнёт {name}',
  'con.online.host': 'Ждём связи с создателем комнаты…',
  'con.online.took': 'Вы заняли место компьютера — его карты теперь ваши',
  'con.away': 'нет связи',
  'con.away.status': '{name}: нет связи — ждём, скоро подменит компьютер',
  'con.away.wait': '{name}: нет связи — ждём',
  'con.watch': 'Мест нет — вы смотрите партию',
  'con.say.join': ['Я в игре!', 'Привет всем!', 'Подвиньтесь'],
  'con.b.shuffle': 'вперемешку',
  'con.b.ready': 'готово!',
  'con.b.fight': 'в бой!',
  'con.b.swap': 'обмен',
  'con.b.pass': 'пас',
  'con.b.respond': 'отбиться!',
  'con.b.decline': 'отказаться',
  'con.b.accept': 'по рукам',
  'con.b.reject': 'нет',
  'con.h.setup': 'Нажимайте на карту, чтобы сменить тип',
  'con.h.setup2': 'Соперники не узнают, что где, пока карта не выйдет в бой.',
  'con.h.pick': 'выберите свою карту',
  'con.h.target': 'теперь — соперника (нажмите на его карты)',
  'con.h.go': 'бой или обмен на отмеченную чужую карту',
  'con.h.defend': 'выберите карту, которой ответите',
  'con.h.defend2': 'выберите карту — или откажитесь от реванша',
  'con.h.trade': 'отдать свою — получить его?',
  'con.h.wait': 'ждём…',
  'con.a.challenge': 'Вызов на бой: {a} → {b}',
  'con.a.offer': 'Предложение обмена: {a} → {b}',
  'con.a.give': 'отдаёт',
  'con.a.want': 'просит',
  'con.a.start': 'Первый ход — {name}',
  'con.a.waitsetup': 'Каждый тайно размечает свои 10 карт',
  'con.ready': 'готово',
  'con.r.win': '{name} забирает обе карты',
  'con.r.tie': 'Ровно — карты остаются у хозяев',
  'con.e.decline': 'Реванша не будет: {b} отказывается',
  'con.e.deal': 'Обмен: {a} и {b} меняются картами',
  'con.e.nodeal': '{b} не соглашается на обмен',
  'con.e.pass': '{a} пропускает ход',
  'con.win': 'Побеждает {name}!',
  'con.tie': 'Ничья!',
  'con.score.sub': 'очки: {s}',
  'con.say.fight': ['К барьеру!', 'Сразимся?', 'Защищайся!', 'Бой!'],
  'con.say.scared': ['Ой', 'Хм…', 'Ну держись', 'Опять?'],
  'con.say.won': ['Моё!', 'Беру!', 'Спасибо!', 'Хе-хе', 'Как по нотам'],
  'con.say.big': ['Десяточка!', 'Вот это улов!', 'Джекпот!'],
  'con.say.back': ['С возвращением!', 'Блудная карта вернулась'],
  'con.say.lost': ['Эх…', 'Ну вот', 'Отдавай…', 'Промах'],
  'con.say.tie': ['Ничья?!', 'Великие умы…', 'Синхронно!'],
  'con.say.decline': ['Не сейчас', 'В другой раз', 'Мы уже бились'],
  'con.say.refused': ['Трусишка!', 'Ну и ладно', 'Пф'],
  'con.say.offer': ['Меняемся?', 'Моя на вашу?', 'Есть дело…'],
  'con.say.deal': ['По рукам!', 'Идёт!', 'Сделка!'],
  'con.say.nodeal': ['Не-а', 'Без меня', 'Нашли дурака'],
  'con.say.pass': ['Я подожду', 'Пас', 'Пока посмотрю'],
  'con.say.win': ['Ура!', 'Афера века!', 'Я гений'],
  'con.say.lose': ['Реванш?', 'Обвели вокруг пальца', 'В следующий раз…'],
  'con.h.how': 'Как играть',
  'con.how': `
    <p><b>Что нужно:</b> 2–4 игрока. У каждого 10 карт со своим именем (здесь — своим цветом), номера от 1 до 10.</p>
    <p><b>Подготовка.</b> Каждый тайно помечает свои карты: <b>камень</b>, <b>ножницы</b> или <b>бумага</b> — в любой пропорции, хоть все десять ножницами.</p>
    <p><b>Ход.</b> Сначала можно предложить <b>один обмен</b>: своя карта на конкретную чужую — тот, кого просят, соглашается или нет. Потом вызовите кого-нибудь на <b>бой</b> или скажите «пас».</p>
    <p><b>Бой.</b> Оба тайно выбирают по карте и открывают. Камень бьёт ножницы, ножницы — бумагу, бумага — камень. Если тип одинаковый — побеждает больший номер, если совпал и номер — карты остаются у хозяев. <b>Победитель забирает обе карты.</b></p>
    <p>Кто чья карта и с каким номером — видят все. А вот тип остаётся секретом, пока карту не откроют в бою; ещё его узнаёт тот, к кому карта попала при обмене.</p>
    <p>У кого не осталось карт, тот пропускает ходы.</p>
    <p><b>Отказ (3–4 игрока).</b> От первого боя отказаться нельзя. От повторного с тем же соперником — можно, пока каждый из вас не сразится с кем-то ещё.</p>
    <p><b>Счёт.</b> После оговорённого числа раундов каждый берёт у себя <b>самую старшую карту каждого соперника</b> (такие помечены звёздочкой) и складывает номера. Свои карты ничего не стоят. У кого больше — тот победил.</p>
    <p><b>Управление:</b> нажмите свою карту, затем карты соперника — и «в бой!». Для обмена отметьте конкретную чужую карту и нажмите «обмен».</p>`,
  'con.h.tips': 'Хитрости',
  'con.tips': `
    <ul>
      <li>Большие номера — самые сильные бойцы и самые дорогие проигрыши: потеряете свою десятку — подарите сопернику 10 очков.</li>
      <li>Свои карты — это патроны, чужие — очки. Воюйте своими, а чужую карту со звёздочкой лишний раз не рискуйте.</li>
      <li>Следите за открытыми картами: если у Красного всплывает сплошной камень, его остальные карты тоже, скорее всего, каменные.</li>
      <li>Выгодный обмен — когда карта лишняя для вас, но нужна другому: например, вторая карта того же соперника, которая всё равно не считается.</li>
      <li>Отбитая своя карта возвращается в строй — она снова может сражаться.</li>
    </ul>
    <p class="tip"><b>Варианты.</b> В жизни «Афера» идёт часами и даже днями — на слёте, в походе, на семейном празднике: новички присоединяются в любой момент, а бои и сделки случаются при встрече. При обмене можно скрывать что угодно, но врать нельзя. А для полного хаоса автор книги советует скрестить игру с «камень-ножницы-бумага-ящерица-Спок».</p>`,
  'con.h.origin': 'Откуда игра',
  'con.origin': `
    <p>Игру придумал Джеймс Эрнест — автор множества недорогих и остроумных настольных игр. Задумана она как «живая»: для конвенций, лагерей и долгих встреч, где играют все сразу и между делом.</p>
    <p>Обычные «камень-ножницы-бумага» — это угадайка на один раз, а здесь к ним добавляются запасы, сделки, блеф и память на то, что уже открывали соперники. Эта версия — пошаговая, для 2–4 игроков и с заранее заданным числом раундов вместо «до ужина».</p>`,
});

addStrings('en', {
  'con.title': 'The Con Game',
  'con.tagline': 'rock-paper-scissors played for cards with names on them',
  'con.players': 'Players:',
  'con.mode': 'Play:',
  'con.mode.pvp': 'people on one screen',
  'con.mode.easy': 'vs computer (easy)',
  'con.mode.normal': 'vs computer (sly)',
  'con.rounds': 'Rounds:',
  'con.again': 'again!',
  'con.p0': 'Blue',
  'con.p1': 'Red',
  'con.p2': 'Green',
  'con.p3': 'Violet',
  'con.cpu1': 'Slick',
  'con.cpu2': 'Shifty',
  'con.cpu3': 'Dodger',
  'con.pts': ['point', 'points'],
  'con.cards': ['card', 'cards'],
  'con.type0': 'rock',
  'con.type1': 'paper',
  'con.type2': 'scissors',
  'con.round': 'round {r} of {n}',
  'con.turn': '{name}: your turn · {round}',
  'con.turn.you': 'Your turn · {round}',
  'con.turn.them': '{name} is moving…',
  'con.thinking': '{name} is thinking…',
  'con.defend': '{name}, you’re challenged!',
  'con.defend.you': 'You’re challenged!',
  'con.trade.you': 'You’ve got a swap offer',
  'con.trade.them': '{name} considers the swap…',
  'con.setup.you': 'Mark your cards',
  'con.setup.name': '{name}: mark your cards',
  'con.setup.wait': 'Opponents are marking their cards…',
  'con.cover.status': 'Next: {name}',
  'con.cover.title': 'Pass the device',
  'con.cover.note': 'everyone else — no peeking!',
  'con.cover.btn': 'It’s me — show my cards',
  'con.online.wait': 'Waiting for the other player…',
  'con.online.note': 'The room creator picks the number of players and rounds and starts new games. With 3–4 players the computer plays the free seats; whoever joins mid-game takes over a computer seat, cards and all.',
  'con.online.waitnew': '{name} will start the next game',
  'con.online.host': 'Waiting for the room creator…',
  'con.online.took': 'You took over a computer seat — its cards are yours now',
  'con.away': 'offline',
  'con.away.status': '{name} is offline — waiting, the computer will step in soon',
  'con.away.wait': '{name} is offline — waiting',
  'con.watch': 'No free seats — you are watching',
  'con.say.join': ['I’m in!', 'Hi all!', 'Move over'],
  'con.b.shuffle': 'shuffle',
  'con.b.ready': 'ready!',
  'con.b.fight': 'fight!',
  'con.b.swap': 'swap',
  'con.b.pass': 'pass',
  'con.b.respond': 'fight back!',
  'con.b.decline': 'refuse',
  'con.b.accept': 'deal',
  'con.b.reject': 'no',
  'con.h.setup': 'Tap a card to change its type',
  'con.h.setup2': 'Nobody learns what’s what until a card enters a fight.',
  'con.h.pick': 'pick one of your cards',
  'con.h.target': 'now an opponent (tap their cards)',
  'con.h.go': 'fight, or swap for the marked card',
  'con.h.defend': 'pick the card you’ll answer with',
  'con.h.defend2': 'pick a card — or refuse the rematch',
  'con.h.trade': 'give yours, get theirs?',
  'con.h.wait': 'waiting…',
  'con.a.challenge': '{a} challenges {b}',
  'con.a.offer': '{a} offers {b} a swap',
  'con.a.give': 'gives',
  'con.a.want': 'wants',
  'con.a.start': '{name} goes first',
  'con.a.waitsetup': 'Everyone secretly marks their 10 cards',
  'con.ready': 'ready',
  'con.r.win': '{name} takes both cards',
  'con.r.tie': 'Dead even — cards go back',
  'con.e.decline': '{b} refuses a rematch with {a}',
  'con.e.deal': 'Swap: {a} and {b} trade cards',
  'con.e.nodeal': '{b} turns the swap down',
  'con.e.pass': '{a} passes',
  'con.win': '{name} wins!',
  'con.tie': 'A tie!',
  'con.score.sub': 'points: {s}',
  'con.say.fight': ['En garde!', 'Fight me!', 'Draw!', 'Let’s go!'],
  'con.say.scared': ['Uh-oh', 'Hmm…', 'Bring it', 'Again?'],
  'con.say.won': ['Mine!', 'Gotcha!', 'Thanks!', 'Heh', 'Like clockwork'],
  'con.say.big': ['A ten!', 'What a catch!', 'Jackpot!'],
  'con.say.back': ['Welcome home!', 'The prodigal card returns'],
  'con.say.lost': ['Ugh…', 'Oh no', 'Hand it over…', 'Wrong guess'],
  'con.say.tie': ['A tie?!', 'Great minds…', 'In sync!'],
  'con.say.decline': ['Not now', 'Some other time', 'We just fought'],
  'con.say.refused': ['Chicken!', 'Fine', 'Pfft'],
  'con.say.offer': ['Swap?', 'Mine for yours?', 'Got a deal…'],
  'con.say.deal': ['Deal!', 'You’re on!', 'Shake on it'],
  'con.say.nodeal': ['Nope', 'Count me out', 'Nice try'],
  'con.say.pass': ['I’ll wait', 'Pass', 'Just watching'],
  'con.say.win': ['Hooray!', 'Con of the century!', 'I’m a genius'],
  'con.say.lose': ['Rematch?', 'I got conned', 'Next time…'],
  'con.h.how': 'How to play',
  'con.how': `
    <p><b>You need:</b> 2–4 players. Each owns 10 cards with their name on them (here: their colour), numbered 1 to 10.</p>
    <p><b>Setup.</b> Everyone secretly marks each of their cards <b>rock</b>, <b>paper</b> or <b>scissors</b> — any mix you like, even ten scissors.</p>
    <p><b>Your turn.</b> First you may make <b>one swap offer</b>: one of your cards for a specific card of someone else’s — they accept or refuse. Then <b>challenge</b> someone to a fight, or pass.</p>
    <p><b>Fights.</b> Both players secretly choose a card and reveal. Rock beats scissors, scissors beat paper, paper beats rock. Same type — the higher number wins; same number too — nothing changes hands. <b>The winner keeps both cards.</b></p>
    <p>Everybody can see who holds which card and its number. The type stays secret until the card is shown in a fight; a swap also shows it to whoever receives the card.</p>
    <p>A player with no cards left skips their turns.</p>
    <p><b>Refusing (3–4 players).</b> You can’t refuse a first fight. You may refuse a rematch with the same opponent until each of you has fought someone else.</p>
    <p><b>Scoring.</b> After the agreed number of rounds, take the <b>highest card from each opponent</b> in your hand (marked with a star) and add up the numbers. Your own cards are worth nothing. Highest total wins.</p>
    <p><b>Controls:</b> tap one of your cards, then an opponent’s cards, and press “fight!”. To swap, mark a specific card of theirs and press “swap”.</p>`,
  'con.h.tips': 'Tricks',
  'con.tips': `
    <ul>
      <li>High numbers are the strongest fighters and the costliest losses: lose your own 10 and you hand the opponent 10 points.</li>
      <li>Your own cards are ammunition, other people’s cards are points. Fight with your own; don’t risk a starred card without a reason.</li>
      <li>Watch what gets revealed: if Red keeps showing rocks, Red’s other cards are probably rocks too.</li>
      <li>A good swap gives away something useless to you but useful to them — say, a second card from the same opponent that doesn’t count anyway.</li>
      <li>Win back one of your own cards and it’s ammunition again.</li>
    </ul>
    <p class="tip"><b>Variants.</b> In real life the Con Game runs for hours or days — at a retreat, a camp, a family reunion: newcomers join any time, and fights and deals happen whenever two players meet. When trading you may hide anything you like, but you may not lie. For extra chaos, the book suggests crossing it with rock-paper-scissors-lizard-Spock.</p>`,
  'con.h.origin': 'Where it comes from',
  'con.origin': `
    <p>The game was designed by James Ernest, the author of a whole shelf of cheap and clever tabletop games. It was meant as a “live” game for conventions, camps and long gatherings, where everyone plays at once, in between everything else.</p>
    <p>Plain rock-paper-scissors is a one-off guess; here it gains stockpiles, deals, bluffing and a memory for what your rivals have already shown. This version is turn-based, for 2–4 players, with a fixed number of rounds instead of “until dinner”.</p>`,
});
