// Regenerates policy.js: the exact win-maximising Pig policy (race to 100, two players).
// Run: node games/pig/make-policy.mjs  (takes a few seconds)
//
// Value iteration over (my score i, opponent score j, turn total k): P = chance that the player to move wins.
// For each (i, j) the best action over k = 1 … 99-i is almost always "roll, hold, roll" (roll while k < f, hold while
// f <= k < r, roll again for the win when k >= r) — stored as two bytes [f, r]. The few pairs where the exact policy
// switches more often are listed in EXTRA as explicit hold intervals [[from, to), …].
import { writeFileSync } from 'node:fs';
import { PIG } from './engine.js';

const T = PIG.TARGET;

function solve(dice) {
  const faces = [1, 2, 3, 4, 5, 6];
  const all = dice === 1 ? faces.map((a) => [a]) : faces.flatMap((a) => faces.map((b) => [a, b]));
  const odds = new Map();
  let pb = 0;
  for (const d of all) {
    const o = PIG.outcome(d);
    if (o.kind === 'bust') pb += 1 / all.length;
    else odds.set(o.g, (odds.get(o.g) || 0) + 1 / all.length);
  }
  const gains = [...odds];
  const P = new Float64Array(T * T * T);
  const at = (i, j, k) => (i * T + j) * T + k;
  const rollP = (i, j, k) => gains.reduce((v, [g, p]) => v + p * (i + k + g >= T ? 1 : P[at(i, j, k + g)]), pb * (1 - P[at(j, i, 0)]));
  const holdP = (i, j, k) => (k > 0 ? 1 - P[at(j, i + k, 0)] : 0);
  for (let delta = 1; delta > 1e-12;) {
    delta = 0;
    for (let i = T - 1; i >= 0; i--) for (let j = T - 1; j >= 0; j--) for (let k = T - 1 - i; k >= 0; k--) {
      const v = Math.max(rollP(i, j, k), holdP(i, j, k)), o = at(i, j, k);
      delta = Math.max(delta, Math.abs(v - P[o]));
      P[o] = v;
    }
  }
  const bands = new Uint8Array(2 * T * T), extra = {};
  for (let i = 0; i < T; i++) for (let j = 0; j < T; j++) {
    const holds = [];                     // hold intervals [from, to)
    for (let k = 1; k < T - i; k++) {
      if (holdP(i, j, k) <= rollP(i, j, k) + 1e-12) continue;
      const last = holds[holds.length - 1];
      if (last && last[1] === k) last[1] = k + 1; else holds.push([k, k + 1]);
    }
    const o = 2 * (i * T + j);
    if (holds.length === 0) { bands[o] = T; bands[o + 1] = T; continue; }
    if (holds.length > 1) extra[`${i},${j}`] = holds;
    [bands[o], bands[o + 1]] = holds[0];
    if (bands[o + 1] === T - i) bands[o + 1] = T;
  }
  return { bands: Buffer.from(bands).toString('base64'), extra };
}

const two = solve(2), one = solve(1);
const head = `// Exact optimal Pig policy (race to ${T}), generated by make-policy.mjs — do not edit by hand.
// For each (my score i, opponent score j): two bytes [f, r] at offset 2*(i*${T}+j): roll while k < f, hold while
// f <= k < r, roll again (going for the win) when k >= r. EXTRA_n lists the few pairs whose exact policy has
// several hold intervals: { 'i,j': [[from, to), …] }.
`;
writeFileSync(new URL('./policy.js', import.meta.url), head +
  `export const POLICY2 = '${two.bands}';\nexport const EXTRA2 = ${JSON.stringify(two.extra)};\n` +
  `export const POLICY1 = '${one.bands}';\nexport const EXTRA1 = ${JSON.stringify(one.extra)};\n`);
console.log('policy.js written; irregular pairs:', Object.keys(two.extra).length, '(two dice),', Object.keys(one.extra).length, '(one die)');
